### PR TITLE
Parallelize codegen execution

### PR DESCRIPTION
**Pull request by cmyr**
This uses rayon to execute multiple codegen tasks in parallel, which is a significant speedup (I'm seeing wall-clock time cut in more than 1/3) for multi-file codegen runs.

running `time cargo run --bin=codegen resources/codegen_plan.toml`:

```
before: 4.43s user 0.61s system 95% cpu 5.262 total
after:  6.68s user 0.73s system 462% cpu 1.603 total
```

### CODE REVIEW

**Comment by rsheeter** [comment]
Would rayon also be recommended for ||ism in compiler?

**Comment by rsheeter** [comment]
I really want to Just Merge!

**Review by rsheeter — APPROVED** [review]
LGTM

**Comment by cmyr** [comment]
> Would rayon also be recommended for ||ism in compiler?

It would definitely be the first thing I would try!

**Pull request merged**
