### PR TITLE
Reduce typo count further.

### PR DESCRIPTION
**Pull request by waywardmonkeys**

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
This leaves a small number of known typos (which are in actual code identifiers). After that, if there's interest, we could enable the same typo check in CI that we use in LineBender repos.

**Comment by waywardmonkeys** [comment]
Rebased to fix merge conflicts.

**Review by cmyr — APPROVED** [review]
thanks!

**Comment by cmyr** [comment]
I think a typo check in CI would be reasonable, if it's simple enough?

**Comment by waywardmonkeys** [comment]
@cmyr Very simple! There's one in `norad` now. I have another PR to file and then I'll do that one and you can see what you think.

**Pull request merged**
