### PR TITLE
[write-fonts] Fix writing of PackedPointNumbers

### PR DESCRIPTION
**Pull request by behdad**
Fixes https://github.com/googlefonts/fontc/issues/313

### CODE REVIEW

**Comment by rsheeter** [comment]
LGTM but can we add a test?

**Review by rsheeter — APPROVED** [review]

**Comment by behdad** [comment]
> LGTM but can we add a test?

That might be above my paygrade currently :D. I'll take a look.

**Comment by behdad** [comment]
> > LGTM but can we add a test?
> 
> That might be above my paygrade currently :D. I'll take a look.

Done.

**Comment by behdad** [comment]
The read-fonts counterpart to this fix is here btw:
https://github.com/googlefonts/fontations/blob/e6f31f06d7c40cde5e9059aa3dd7769875adb41e/read-fonts/src/tables/variations.rs#L253

**Pull request merged**
